<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, useLedger, type Account } from '../../core/api/ledger-context'
import { formatMoney } from '../bills/bill-view-model'
const { ledger, error, loading, canManage, load, run } = useLedger()
const accounts = ref<Account[]>([]), editing = ref(false), archiving = ref<Account|null>(null)
const name = ref(''), type = ref('cash'), balance = ref('0')
const assets = computed(() => accounts.value.reduce((sum,a)=>sum+Math.max(0,a.balance_cents),0))
const liabilities = computed(() => accounts.value.reduce((sum,a)=>sum+Math.max(0,-a.balance_cents),0))
async function refresh() { accounts.value = await api.get<Account[]>(`/ledgers/${ledger.value!.id}/accounts`) }
onMounted(() => run(async()=>{await load();await refresh()}))
async function save() { await run(async()=>{
  if (!/^-?\d{1,9}(\.\d{1,2})?$/.test(balance.value)) throw new Error('请输入有效的期初余额，最多两位小数')
  await api.request(`/ledgers/${ledger.value!.id}/accounts`, { method:'POST',body:JSON.stringify({name:name.value,type:type.value,initial_balance_cents:Math.round(Number(balance.value)*100)}) })
  editing.value=false;name.value='';balance.value='0';await refresh()
}) }
async function archive(){await run(async()=>{await api.request(`/ledgers/${ledger.value!.id}/accounts/${archiving.value!.id}`,{method:'DELETE'});archiving.value=null;await refresh()})}
</script>
<template><main class="page accounts-page"><header class="page-title"><h1>账户</h1><p>{{ledger?.name}} · 清晰掌握每一份资产</p></header><p v-if="error" role="alert" class="error">{{error}}</p><p v-if="loading">正在处理…</p><section class="asset-card"><div class="asset-top"><small>净资产</small></div><h2>¥ {{formatMoney(assets-liabilities)}}</h2><div class="asset-sums"><div><small>总资产</small><strong>¥ {{formatMoney(assets)}}</strong></div><div><small>总负债</small><strong>¥ {{formatMoney(liabilities)}}</strong></div></div></section><div class="section-head"><div><h2>我的账户</h2><span>{{accounts.length}} 个账户</span></div><button v-if="canManage" :disabled="loading" @click="editing=true">＋ 新建</button></div><section class="account-list"><article v-for="account in accounts" :key="account.id" class="account card"><span>💳</span><div><strong>{{account.name}}</strong><small>{{account.type}}</small><button v-if="canManage" :disabled="loading" @click="archiving=account">归档</button></div><b>¥ {{formatMoney(account.balance_cents)}}</b></article><p v-if="!accounts.length && !loading">暂无账户，请先新建账户。</p></section><router-link to="/entry?type=transfer" class="transfer card"><span>⇄</span><div><strong>账户间转账</strong><small>不计入收支，余额更准确</small></div><b>›</b></router-link>
<div v-if="editing" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="新建账户"><h2>新建账户</h2><form @submit.prevent="save"><label>账户名称<input name="name" v-model="name" required maxlength="80"></label><label>类型<select v-model="type"><option value="cash">现金</option><option value="bank">银行卡</option><option value="credit">信用卡</option><option value="payment">支付账户</option><option value="custom">其他</option></select></label><label>期初余额（负数表示负债）<input name="balance" v-model="balance" inputmode="decimal" required></label><p v-if="error" class="error" role="alert">{{error}}</p><button class="primary" :disabled="loading">创建账户</button><button type="button" :disabled="loading" @click="editing=false">取消</button></form></section></div>
<div v-if="archiving" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="归档账户"><h2>归档「{{archiving.name}}」？</h2><p>归档后将不计入账户总览，历史账单仍保留。请先处理账户余额。</p><button class="danger" :disabled="loading" @click="archive">确认归档</button><button @click="archiving=null">取消</button></section></div>
</main></template>
<style scoped>.accounts-page{background:radial-gradient(circle at 20% 0,#e3f5ec,transparent 28%),var(--walnut-bg)}button{border:0}.asset-card{padding:21px;border-radius:25px;color:#fff;background:linear-gradient(140deg,#173f30,#216047);box-shadow:0 15px 32px rgba(22,70,51,.2)}.asset-top{display:flex;justify-content:space-between}.asset-top small{opacity:.7}.asset-top button{background:none;color:rgba(255,255,255,.72);font-size:11px}.asset-card h2{margin:6px 0 17px;font-size:31px}.asset-sums{display:grid;grid-template-columns:1fr 1fr;gap:10px}.asset-sums div{padding:10px 12px;border-radius:14px;background:rgba(255,255,255,.09)}.asset-sums small,.asset-sums strong{display:block}.asset-sums small{opacity:.65;font-size:10px}.asset-sums strong{margin-top:3px}.section-head{display:flex;align-items:end;justify-content:space-between;padding:20px 4px 9px}.section-head h2{display:inline;margin:0 7px 0 0;font-size:17px}.section-head span{color:var(--walnut-muted);font-size:10px}.section-head button{background:none;color:var(--walnut-green);font-weight:800}.account-list{display:grid;gap:9px}.account{display:grid;grid-template-columns:44px 1fr auto;align-items:center;gap:11px;padding:13px}.account>span{width:42px;height:42px;display:grid;place-items:center;border-radius:14px;background:var(--walnut-mint);font-size:18px}.account div strong,.account div small{display:block}.account div small{color:var(--walnut-muted);font-size:10px}.account>b{font-size:14px}.transfer{width:100%;display:grid;grid-template-columns:42px 1fr auto;align-items:center;gap:10px;margin-top:13px;padding:13px;text-align:left}.transfer>span{width:40px;height:40px;display:grid;place-items:center;border-radius:13px;background:#edf4ff;color:var(--walnut-blue);font-size:20px}.transfer div strong,.transfer div small{display:block}.transfer div small{color:var(--walnut-muted);font-size:10px}.transfer>b{color:var(--walnut-muted);font-size:20px}</style>
