<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, useLedger, type Ledger } from '../../core/api/ledger-context'
type Member={user_id:string;username:string;role:'owner'|'editor'|'viewer'}
const { ledger, error, loading, canManage, run }=useLedger()
const ledgers=ref<Ledger[]>([]),members=ref<Member[]>([]),name=ref(''),code=ref(''),invite=ref(''),role=ref('editor')
const preview=ref<{ledger_name:string;owner_name:string;default_role:string}|null>(null)
const pending=ref<{member:Member;action:'remove'|'transfer'}|null>(null)
async function select(item:Ledger){ledger.value=item;sessionStorage.setItem('walnut:ledger',item.id);members.value=[];invite.value='';members.value=await api.get<Member[]>(`/ledgers/${item.id}/members`)}
async function refresh(){ledgers.value=await api.get<Ledger[]>('/ledgers');const selected=ledgers.value.find(item=>item.id===sessionStorage.getItem('walnut:ledger'))??ledgers.value[0];if(selected)await select(selected)}
onMounted(()=>run(refresh))
async function create(){await run(async()=>{const created=await api.request<Ledger>('/ledgers',{method:'POST',body:JSON.stringify({name:name.value})});sessionStorage.setItem('walnut:ledger',created.id);name.value='';await refresh()})}
async function createInvite(){await run(async()=>{const result=await api.request<{code:string}>(`/ledgers/${ledger.value!.id}/invites`,{method:'POST',body:JSON.stringify({default_role:role.value,max_uses:1,expires_at:new Date(Date.now()+7*86400000).toISOString()})});invite.value=result.code})}
async function inspectInvite(){preview.value=null;await run(async()=>{preview.value=await api.get(`/ledger-invites/${encodeURIComponent(code.value.trim())}/preview`)})}
async function join(){await run(async()=>{const result=await api.request<{ledger_id:string}>(`/ledger-invites/${encodeURIComponent(code.value.trim())}/join`,{method:'POST'});sessionStorage.setItem('walnut:ledger',result.ledger_id);code.value='';preview.value=null;await refresh()})}
async function changeRole(member:Member){await run(async()=>{await api.request(`/ledgers/${ledger.value!.id}/members/${member.user_id}`,{method:'PATCH',body:JSON.stringify({role:member.role==='editor'?'viewer':'editor'})});await refresh()})}
async function confirm(){await run(async()=>{const action=pending.value!;const id=ledger.value!.id;await api.request(action.action==='remove'?`/ledgers/${id}/members/${action.member.user_id}`:`/ledgers/${id}/transfer-ownership`,{method:action.action==='remove'?'DELETE':'POST',...(action.action==='transfer'?{body:JSON.stringify({user_id:action.member.user_id})}:{})});pending.value=null;await refresh()})}
</script>
<template><main class="page"><header class="page-title"><router-link to="/bills">‹ 返回账单</router-link><h1>账本管理</h1><p>每个账本的分类、账户与记录独立保存</p></header><p v-if="error" role="alert" class="error">{{error}}</p><p v-if="loading">正在处理…</p>
<section class="card list"><h2>选择账本</h2><div class="toolbar"><button v-for="item in ledgers" :key="item.id" :data-ledger="item.id" :aria-pressed="ledger?.id===item.id" :disabled="loading" @click="run(()=>select(item))">{{item.name}} · {{item.role==='owner'?'所有者':item.role==='editor'?'可编辑':'只读'}}</button></div><form @submit.prevent="create" class="toolbar"><input v-model="name" placeholder="新账本名称" maxlength="80" required aria-label="新账本名称"><button :disabled="loading">创建账本</button></form></section>
<section v-if="ledger" class="card list" style="margin-top:14px"><h2>{{ledger.name}} · {{members.length}} 位成员</h2><article v-for="member in members" :key="member.user_id" class="list-row"><span>{{member.username}} · {{member.role==='owner'?'所有者':member.role==='editor'?'可编辑':'只读'}}</span><div v-if="canManage&&member.role!=='owner'" style="flex-wrap:wrap"><button :disabled="loading" @click="changeRole(member)">{{member.role==='editor'?'设为只读':'允许记账'}}</button><button :disabled="loading" @click="pending={member,action:'remove'}">移除</button><button :disabled="loading" @click="pending={member,action:'transfer'}">移交所有权</button></div></article>
<div v-if="canManage"><h3>邀请成员</h3><div class="toolbar"><select v-model="role" aria-label="受邀成员权限"><option value="editor">可记账</option><option value="viewer">只读</option></select><button :disabled="loading" @click="createInvite">生成邀请码</button></div><p>有效期 7 天，仅可使用 1 次。请仅分享给受邀人。</p><input v-if="invite" :value="invite" readonly aria-label="共享账本邀请码"></div></section>
<section class="card list" style="margin-top:14px"><h2>加入共享账本</h2><form class="toolbar" @submit.prevent="inspectInvite"><input v-model="code" @input="preview=null" placeholder="输入账本邀请码" required aria-label="账本邀请码"><button :disabled="loading">查看邀请</button></form><div v-if="preview"><p>账本：{{preview.ledger_name}} · 邀请人：{{preview.owner_name}} · {{preview.default_role==='editor'?'可记账':'只读'}}</p><button class="primary" :disabled="loading" @click="join">确认加入</button></div></section>
<div v-if="pending" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-label="确认成员变更"><h2>{{pending.action==='remove'?'移除成员':'移交所有权'}}</h2><p>{{pending.action==='remove'?`移除 ${pending.member.username} 后，对方将无法访问此账本。`:`将账本交给 ${pending.member.username} 后，你将失去管理权限。`}}</p><p v-if="error" class="error" role="alert">{{error}}</p><button class="danger" :disabled="loading" @click="confirm">确认操作</button><button :disabled="loading" @click="pending=null">取消</button></section></div>
</main></template>
