<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, useLedger } from '../../core/api/ledger-context'
const { ledger,error,loading,load,run }=useLedger(),members=ref<number|null>(null)
const entries=[{icon:'📒',label:'账本管理',description:'切换账本、邀请与成员权限',path:'/ledgers'},{icon:'🏷️',label:'分类管理',description:'新增、编辑、排序与归档',path:'/categories'},{icon:'💳',label:'账户管理',description:'账户余额与转账',path:'/accounts'},{icon:'🎯',label:'月度预算',description:'设置每月总支出额度',path:'/budgets'},{icon:'⇧',label:'导出数据',description:'CSV 与 JSON 数据副本',path:'/export'},{icon:'🔒',label:'登录设备',description:'查看设备、撤销登录与退出',path:'/devices'}]
onMounted(()=>run(async()=>{const current=await load();members.value=(await api.get<unknown[]>(`/ledgers/${current.id}/members`)).length}))
</script>
<template><main class="page profile-page"><header class="page-title"><h1>我的</h1></header><section class="profile-card"><div class="avatar">核</div><div><h2>核桃记账</h2><p>联网保存到 Cloudflare · 不代表已完成离线同步</p></div></section><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="loading">正在读取账本…</p><section class="ledger-card card"><div><span>当前账本</span><strong>{{ledger?.name || '未选择'}}</strong></div><span v-if="members!==null" class="people">👤 {{members}} 位成员</span><router-link to="/ledgers">切换 ›</router-link></section><section class="menu card"><router-link v-for="item in entries" :key="item.path" :to="item.path"><span class="menu-icon">{{item.icon}}</span><div><strong>{{item.label}}</strong><small>{{item.description}}</small></div><b>›</b></router-link></section><section class="card list"><h3>尚未完成的功能</h3><p>账单导入、周期账单、标签、离线同步与备份恢复仍待实现或验收，不作为可用功能展示。</p></section><p class="version">旧版本机数据未删除，尚未自动迁移到云端。</p></main></template>
<style scoped>.profile-page{background:radial-gradient(circle at 80% 0,#e6f8ef,transparent 30%),var(--walnut-bg)}button{border:0;background:none}.profile-card{display:grid;grid-template-columns:56px 1fr auto;align-items:center;gap:13px;padding:18px;margin-bottom:12px;border:1px solid #dbece3;border-radius:23px;background:linear-gradient(145deg,#e9f8f1,#fff);box-shadow:var(--walnut-shadow)}.avatar{width:54px;height:54px;display:grid;place-items:center;border-radius:18px;background:linear-gradient(145deg,var(--walnut-green-2),var(--walnut-green));color:#fff;font-size:22px;font-weight:900}.profile-card h2{margin:0;font-size:18px}.profile-card p{display:flex;align-items:center;gap:3px;margin:4px 0 0;color:var(--walnut-muted);font-size:10px}.profile-card button{color:var(--walnut-muted);font-size:23px}.ledger-card{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:9px;padding:14px 15px;margin-bottom:12px}.ledger-card div span,.ledger-card div strong{display:block}.ledger-card div span{color:var(--walnut-muted);font-size:9px}.ledger-card .people{padding:5px 8px;border-radius:9px;background:var(--walnut-mint);color:var(--walnut-deep);font-size:9px}.ledger-card button{color:var(--walnut-green);font-size:11px}.menu{padding:0 14px;margin-bottom:12px}.menu a{display:grid;grid-template-columns:36px 1fr auto;align-items:center;gap:10px;padding:12px 0}.menu a+a{border-top:1px solid var(--walnut-line)}.menu-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:var(--walnut-mint)}.menu strong,.menu small{display:block}.menu strong{font-size:13px}.menu small{color:var(--walnut-muted);font-size:9px}.menu b{color:#a2aca7;font-size:18px}.version{text-align:center;color:#a1aaa6;font-size:9px}</style>
