name = "walnut-ledger-api"
main = "src/app.ts"
compatibility_date = "2026-09-21"

[[d1_databases]]
binding = "DB"
database_name = "walnut-ledger"
database_id = "3c629cbf-3aaa-4f1b-bac3-6ff74d4b37bb"
migrations_dir = "migrations"

[vars]
PASSWORD_ITERATIONS = "210000"

[triggers]
crons = ["17 3 * * *"]
